"use server";

import { revalidatePath } from "next/cache";
import { getServerConfig } from "@/lib/config";
import { errorMessage } from "@/lib/error-message";
export type EquipmentActionState = { ok: boolean; message?: string; fieldErrors?: Record<string, string[] | undefined> };
async function context() { const [{ db }, { createOrganizationRepository }, { createEquipmentRepository }, { createEquipmentService }] = await Promise.all([import("@/server/db"), import("@/server/db/organizations"), import("@/server/db/equipment"), import("@/server/services/equipment")]); const organization = await createOrganizationRepository(db).getOrCreateInitial({ name: "G.Lab Studio", timezone: getServerConfig().appTimezone }); return { organization, service: createEquipmentService(createEquipmentRepository(db)) }; }
const optional = (fd: FormData, key: string) => { const value = fd.get(key); return typeof value === "string" && value.trim() ? value : null; };
const input = (fd: FormData) => ({ name: String(fd.get("name") ?? ""), category: optional(fd, "category"), assetCode: optional(fd, "assetCode"), serialNumber: optional(fd, "serialNumber"), status: String(fd.get("status") ?? "available"), notes: optional(fd, "notes") });
export async function createEquipmentAction(_state: EquipmentActionState, fd: FormData): Promise<EquipmentActionState> { try { const { organization, service } = await context(); const result = await service.create(organization.id, input(fd)); if (!result.ok) return { ok: false, message: result.error.message, fieldErrors: result.error.fieldErrors }; revalidatePath("/equipment"); return { ok: true, message: "Equipment item created." }; } catch (error) { return { ok: false, message: errorMessage(error, "Unable to create equipment item.") }; } }
export async function updateEquipmentAction(id: string, _state: EquipmentActionState, fd: FormData): Promise<EquipmentActionState> { try { const { organization, service } = await context(); const result = await service.update(organization.id, id, input(fd)); if (!result.ok) return { ok: false, message: result.error.message, fieldErrors: result.error.fieldErrors }; revalidatePath("/equipment"); revalidatePath(`/equipment/${id}`); return { ok: true, message: "Equipment item updated." }; } catch (error) { return { ok: false, message: errorMessage(error, "Unable to update equipment item.") }; } }
