"use server";

import { revalidatePath, revalidateTag } from "next/cache";
import { getServerConfig } from "@/lib/config";
import { errorMessage } from "@/lib/error-message";
import type { DeleteActionState } from "@/components/ui/delete-entity-button";
import { CALENDAR_EQUIPMENT_OPTIONS_TAG } from "@/server/calendar-filter-options";
import { SHOOT_DETAIL_EQUIPMENT_OPTIONS_TAG } from "@/server/shoot-detail-options";
export type EquipmentActionState = { ok: boolean; message?: string; messageVi?: string; messageEn?: string; fieldErrors?: Record<string, string[] | undefined> };
async function context() { const [{ db }, { createOrganizationRepository }, { createEquipmentRepository }, { createEquipmentService }] = await Promise.all([import("@/server/db"), import("@/server/db/organizations"), import("@/server/db/equipment"), import("@/server/services/equipment")]); const organization = await createOrganizationRepository(db).getOrCreateInitial({ name: "G.Lab Studio", timezone: getServerConfig().appTimezone }); return { organization, service: createEquipmentService(createEquipmentRepository(db)) }; }
const optional = (fd: FormData, key: string) => { const value = fd.get(key); return typeof value === "string" && value.trim() ? value : null; };
const input = (fd: FormData) => ({ name: String(fd.get("name") ?? ""), category: optional(fd, "category"), assetCode: optional(fd, "assetCode"), serialNumber: optional(fd, "serialNumber"), status: String(fd.get("status") ?? "available"), notes: optional(fd, "notes"), imageDataUrl: optional(fd, "imageDataUrl") });
export async function createEquipmentAction(_state: EquipmentActionState, fd: FormData): Promise<EquipmentActionState> { try { const { organization, service } = await context(); const result = await service.create(organization.id, input(fd)); if (!result.ok) return { ok: false, messageVi: result.error.code === "NOT_FOUND" ? "Không tìm thấy thiết bị." : "Dữ liệu thiết bị chưa hợp lệ.", messageEn: result.error.message, fieldErrors: result.error.fieldErrors }; revalidatePath("/equipment"); revalidateTag(CALENDAR_EQUIPMENT_OPTIONS_TAG); revalidateTag(SHOOT_DETAIL_EQUIPMENT_OPTIONS_TAG); return { ok: true, messageVi: "Đã thêm thiết bị.", messageEn: "Equipment item created." }; } catch (error) { console.error("createEquipmentAction", error); return { ok: false, messageVi: "Không thể thêm thiết bị lúc này.", messageEn: "Unable to create equipment item." }; } }
export async function updateEquipmentAction(id: string, _state: EquipmentActionState, fd: FormData): Promise<EquipmentActionState> { try { const { organization, service } = await context(); const result = await service.update(organization.id, id, input(fd)); if (!result.ok) return { ok: false, messageVi: result.error.code === "NOT_FOUND" ? "Không tìm thấy thiết bị." : "Dữ liệu thiết bị chưa hợp lệ.", messageEn: result.error.message, fieldErrors: result.error.fieldErrors }; revalidatePath("/equipment"); revalidatePath(`/equipment/${id}`); revalidateTag(CALENDAR_EQUIPMENT_OPTIONS_TAG); revalidateTag(SHOOT_DETAIL_EQUIPMENT_OPTIONS_TAG); return { ok: true, messageVi: "Đã cập nhật thiết bị.", messageEn: "Equipment item updated." }; } catch (error) { console.error("updateEquipmentAction", error); return { ok: false, messageVi: "Không thể cập nhật thiết bị lúc này.", messageEn: "Unable to update equipment item." }; } }
export async function deleteEquipmentAction(id: string, _state: DeleteActionState, _formData: FormData): Promise<DeleteActionState> { try { const { organization, service } = await context(); const result = await service.remove(organization.id, id); if (!result.ok) return { ok: false, messageVi: "Không tìm thấy thiết bị.", messageEn: "Equipment item not found." }; revalidatePath("/equipment"); revalidatePath("/shoots"); revalidateTag(CALENDAR_EQUIPMENT_OPTIONS_TAG); revalidateTag(SHOOT_DETAIL_EQUIPMENT_OPTIONS_TAG); return { ok: true }; } catch (error) { console.error("deleteEquipmentAction", error); return { ok: false, messageVi: "Không thể xóa thiết bị vì vẫn đang được đặt cho buổi quay. Hãy gỡ các lịch đặt trước.", messageEn: "This equipment item is still booked for shoots. Remove those bookings first." }; } }
